### ISSUE TITLE
Error Connecting GitHub to MLSA Account 

### ISSUE THREAD

**Issue by gmwangomo** [microsoft/SATechnicalOnboarding#101]
Hello,

I face the same issue how to fix it

**Comment by kakusu243** [comment]
Please give me more details!!

**Comment by AnthonyByansi** [comment]
Hi @gmwangomo, could you please take a screenshot of the issue you are facing so we can help?

**Comment by gmwangomo** [comment]
Oooh thanks but I was fixed the issue, sorry  i forget to remove the issue
