### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by hzjadoon** [microsoft/SATechnicalOnboarding#105]
For technical Onboarding my site is completed and leads my resume properly, but I am receiving mails of failure in deployment, so what should I do?
![WhatsApp Image 2024-02-04 at 13 56 39_bbcd6f82](https://github.com/microsoft/SATechnicalOnboarding/assets/128807819/93446b6a-5b60-4389-85e5-10184c25663f)

**Comment by AnthonyByansi** [comment]
Hi @hzjadoon I believe this has been addressed here https://github.com/microsoft/SATechnicalOnboarding/discussions/20#discussioncomment-8361651, please check it out
