### ISSUE TITLE
There is no pull request in your second link

### ISSUE THREAD

**Issue by Vaibhavghugretkar** [microsoft/SATechnicalOnboarding#108]
I'm getting this message from the evaluator saying that -  there is no pull request in your second link, the link should lead to a GitHub page that says, “Update the game over message” and have a purple button labeled “Merged” under it.

**Comment by AnthonyByansi** [comment]
Hi @Vaibhavghugretkar 
You need to complete the github training as part of your technical onboarding. Re-visit the technical onboarding instructions and Complete the[ github training](https://learn.microsoft.com/training/modules/introduction-to-github/?WT.mc_id=%3Fwt.mc_id%3Dstudentamb_260352). At the end, Complete the exercises and you need to submit a link that shows you made your first pull request merged, and that will be purple..
