### ISSUE TITLE
Technical Onboarding channel Link not working

### ISSUE THREAD

**Issue by LinqingZ** [microsoft/SATechnicalOnboarding#11]
Hi, the link for the Technical Onboarding channel is not working at all from either the onboarding on Team or the GitHub repo here.

**Comment by Brenda-mwaura** [comment]
Hi, The technical onboarding link is not working

**Comment by thebarshablog** [comment]
@Brenda-mwaura, I got accepted into the program today. I'm looking forward to join the onboarding channel and having the same issue! Were you able to join?

**Comment by Brenda-mwaura** [comment]
Hi,
No I wasn't able to join but I'm sure they are fixing it.

**Comment by tessawiedmann** [comment]
Hi! Thanks for raising this issue. I confirmed that the link does work, you just have to be logged in with your @studentambassadors.com email address. I added a sentence in the Readme to make this more clear. Thanks for the feedback :)

**Comment by Brenda-mwaura** [comment]
Awesome, thanks!
