### ISSUE TITLE
ERROR : No access to github copilot found

### ISSUE THREAD

**Issue by Tehreemfatima489** [microsoft/SATechnicalOnboarding#110]
Hey,

I am having this error while creating my portfolio site on github codespace for my technical onboarding. And there I am recieving this error? What should I do? 

Anyone kindly guide me?

![error](https://github.com/microsoft/SATechnicalOnboarding/assets/68489885/15a2eb31-2b5c-4856-ae23-d445be79ee21)

**Comment by AnthonyByansi** [comment]
Hi @Tehreemfatima489  the error indicates that you don't have access to github copilot, follow this step by step guide on how to redeem your [GitHUb copilot for students](https://techcommunity.microsoft.com/t5/educator-developer-blog/step-by-step-setting-up-github-student-and-github-copilot-as-an/ba-p/3736279?WT.mc_id=%3Fwt.mc_id%3Dstudentamb_260352)

**Comment by Tehreemfatima489** [comment]
@AnthonyByansi Is it necessary for technical onboarding? because I have done everything from instructions. and now my website is waiting for deployment and my commit is queued for 10 hours. Is it because of I do not have Github Copilot?

**Comment by AnthonyByansi** [comment]
GitHub Copilot isn't a necessity for you to complete your technical onboarding. 
The instructions provide all you need to accomplish your technical onboarding. Please make sure you have your changes pushed to the `main branch` If you run into further issues, please DM me on teams so I can help

**Comment by Tehreemfatima489** [comment]
@AnthonyByansi Thank you. I have solved the issue and completed my technical onboarding
