### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by adithishetty31** [microsoft/SATechnicalOnboarding#113]
I have deployed the site but the status is showed that 'waiting for deployment ' since 2-3 days.
![Screenshot_20240221_122442_Chrome](https://github.com/microsoft/SATechnicalOnboarding/assets/131400873/5c02b286-f116-418f-96c8-672cfa95e775)

**Comment by AnthonyByansi** [comment]
Hi @adithishetty31 It looks like your deployment details weren't set right. Pleasure you've gat the following details during your site deployment.

Choose `React` as your Build Preset
![301968449-0ef7bcb2-3937-4f26-9834-38fae18c5b19](https://github.com/microsoft/SATechnicalOnboarding/assets/101401469/8a3bb877-dfa8-4668-aaf3-53266587fce4)

Change the `output location` from the default build to `dist`
![301968770-0f067bff-607c-4186-b36b-834bbad46d97](https://github.com/microsoft/SATechnicalOnboarding/assets/101401469/c765e4ec-8cae-444b-b0a1-3b69635b621e)

**Comment by AnthonyByansi** [comment]
Please, should land in further issues, don't hesitate to reach out on Teams (Byansi Anthony) so I can help!
