### ISSUE TITLE
Website not working only white page will be shown 

### ISSUE THREAD

**Issue by balasubramaniyamofficial** [microsoft/SATechnicalOnboarding#115]
In technical onboarding I will create my portfolio in GitHub in GitHub the portfolio will be working once I will publish the website is not working the website

Uploading video_1708634496465.mp4…

**Comment by AnthonyByansi** [comment]
hi @balasubramaniyamofficial Unfortunately I couldn't get your query. Could you please take a screenshot of the issue you're facing we can help?

**Comment by balasubramaniyamofficial** [comment]
https://salmon-forest-02cabbd00.4.azurestaticapps.net 


This is white page problem

**Comment by balasubramaniyamofficial** [comment]
![Screenshot_2024-02-23-09-04-46-19_f56466bc4bb61e6d2de1f3b0468a89d9.jpg](https://github.com/microsoft/SATechnicalOnboarding/assets/116048313/c8163bd2-858c-43bf-a1ca-64b779d33f0d)

![Screenshot_2024-02-23-09-04-36-31_f56466bc4bb61e6d2de1f3b0468a89d9.jpg](https://github.com/microsoft/SATechnicalOnboarding/assets/116048313/e8b6258d-bb75-494c-965c-bba4cc71425d)

**Comment by AnthonyByansi** [comment]
Hi @balasubramaniyamofficial,  I can see that the URL that points to your portfolio is broken. This might be as a result of not setting up the deployment process correctly. 
Please follow the following [section](https://github.com/microsoft/SATechnicalOnboarding/blob/main/technical-onboarding-instructions.md#optional-creating-an-azure-static-web-app-from-an-existing-github-respository) of the technical onboarding instructions, you will have your portfolio site deployed correctly.

Also, I see the last screenshot you took has something to do with github pages, please note that you are meant to deploy on `Azure` and not ~github pages~
