### ISSUE TITLE
No merge on github 

### ISSUE THREAD

**Issue by laibahere** [microsoft/SATechnicalOnboarding#116]
I have been in contact with the SA coordinator. In task two of technical onboarding, they are saying I haven't merged but in the repo insights I am getting that I have Merged my request![20240224_113618.jpg](https://github.com/microsoft/SATechnicalOnboarding/assets/110159691/bbded3dc-c43b-4e2a-a336-9ab6224b9949)

**Comment by AnthonyByansi** [comment]
Hi @laibahere Please note that [introductions to GitHub](https://github.com/skills/introduction-to-github) is part of your technical onboarding process.

Steps you need to accomplish for the course are;

1. Create a branch
2. Commit a file
3. Open a pull request
4. Merge your pull request

Be sure to complete all the steps and at the end of exercise, you are told to merge the `pull request` made, share with the SA-coordinator, the URL to merged pull request. 

Please, should you need any clarification, don't hesitate to reach out on Teams (Byansi Anthony) for assistance.
