### ISSUE TITLE
Technical Onboarding

### ISSUE THREAD

**Issue by Mr-mahato** [microsoft/SATechnicalOnboarding#117]
I have reached to alpha in MLSA , and i have completed one technical onboarding while i was in microsoft learn student phase , which was of to create a protofolio . Now i got a mail and it is tailing me to complete technical onboarding in alpha . do i need to complete that still?

**Comment by AnthonyByansi** [comment]
Hi @Mr-mahato Please note that for Alpha advancement, you need to complete any of these [learn paths](https://stdntpartners-my.sharepoint.com/:o:/r/personal/flow_studentambassadors_com/Documents/Notebooks/Learn%20Paths?d=w50c61c8364534a588fd92d7cf3e53307&csf=1&web=1&e=iS96LI)

Technical onboarding is one of the perquisites for Beta Advancement. If you completed your technical onboarding, please have the [technical onboarding completion form](https://forms.office.com/r/UnJgmjap4U) filled

I hope that answers your query, please don't hesitate to reach out incase you need any further assistance
