### ISSUE TITLE
Deployment issue dist invalid

### ISSUE THREAD

**Issue by aanyasinghdhaka** [microsoft/SATechnicalOnboarding#121]
Try to validate location at: '/github/workspace/dist'.
App Directory Location: 'dist' is invalid. Could not detect this directory. Please verify your workflow file reflects your repository structure.

**Comment by AnthonyByansi** [comment]
Hi @aanyasinghdhaka Could you please share a screenshot of the issue you're facing so I could better understand where that is coming from?

I would be happy to help!

**Comment by aanyasinghdhaka** [comment]
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/122288528/ef03c83a-2a98-46e9-a751-12da172793f0)
