### ISSUE TITLE
Unable to get the subscription for azure account

### ISSUE THREAD

**Issue by MAYANK12SHARMA** [microsoft/SATechnicalOnboarding#127]
When i open the 'https://my.visualstudio.com/benefits' page. on this page instead of showing 'ACTIVATE' your azure $150 it shows "Try for Free' and when i click on on it ask for 'verification of card'. Also when i log in with different account showing the same. 
please Help me.

![azure](https://github.com/microsoft/SATechnicalOnboarding/assets/145884197/6ea49ebd-a32d-4fa1-ab8f-3a8cda1d91c3)

**Comment by AnthonyByansi** [comment]
Hi @MAYANK12SHARMA 
To redeem the `$150 Azure monthly Credits`, you need to have advanced to Alpha and you login to the [Visual Studio Subscription ](https://my.visualstudio.com/) Dashboard with your Ambassador account. 
![Screenshot 2024-04-21 211736](https://github.com/microsoft/SATechnicalOnboarding/assets/101401469/1346df00-7d1f-4adf-b955-a5cc8d32d84a)

Please don't hesitate to reach out in case you have further inquiries.

**Comment by MAYANK12SHARMA** [comment]
Hi Anthony Byansi, 
I am already signing with my ambassadors id, still showing....
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/145884197/d932bd49-c7a2-4dc0-aa99-21dd3d97e7f3)
and when i click on 'MAYANK SHARMA' it show the follwing picture 
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/145884197/2b2350e9-3492-4c6f-869f-0e7f3d44c8ff)

and below is my ambassador profile, 
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/145884197/1ac0474e-5c0a-4c05-bb47-89bca86bfcd9)

could you please further assist me why i am unable to redeem my subscription , i also completed the learning path.
Thanks

**Comment by AnthonyByansi** [comment]
Hi @MAYANK12SHARMA 

It seems your Azure credits offer hasn't been activated yet, since you've just been onboarded. Could you please sign up for the [Azure for students credits](https://azure.microsoft.com/free/students/?WT.mc_id=%3Fwt.mc_id%3Dstudentamb_260352) with your university email.

![image](https://github.com/microsoft/SATechnicalOnboarding/assets/101401469/63af3c71-c92d-40e7-a044-070004943eef)

Should you encounter any additional issues, please feel free to contact me through Teams for further assistance.

**Comment by MdNadeemSarwar** [comment]
Hi @AnthonyByansi when I try to verify my account using my credit card every time we get this types of error I am not able to activate my Azure account can you please help me 
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/107212111/50156e2b-0ebc-483b-bc76-aca79d9b2085)

**Comment by AnthonyByansi** [comment]
Hi @MdNadeemSarwar had you tried out the Azure for students Option: https://github.com/microsoft/SATechnicalOnboarding/issues/127#issuecomment-2069239297 ? Well, it doesn't require a Credit card. Only your University/college email.

**Comment by MdNadeemSarwar** [comment]
ok

**Comment by AnthonyByansi** [comment]
@MdNadeemSarwar Inform me of any issues you encounter so that I can provide better assistance.
