### ISSUE TITLE
Sku is invalid. This subscription has too many static sites with SKU : Free.

### ISSUE THREAD

**Issue by mukprabhakar** [microsoft/SATechnicalOnboarding#131]
![Screenshot 2024-04-24 235932](https://github.com/microsoft/SATechnicalOnboarding/assets/133365427/4b9e5384-c022-4244-9bd7-154ffb391a68)
I had tried many times to but all the times show this error "Sku is invalid. This subscription has too many static sites with SKU : Free."

**Comment by AnthonyByansi** [comment]
Hi @mukprabhakar Could you please provide some context to the issue you're experiencing, such as a screenshot? This will help us better understand your problem and assist you. 
Thank you.

**Comment by mukprabhakar** [comment]
![Screenshot 2024-04-24 235932](https://github.com/microsoft/SATechnicalOnboarding/assets/133365427/c421a6f6-3e8e-4eb6-a206-783f7b93ff90)

**Comment by AnthonyByansi** [comment]
Hi @mukprabhakar 
It appears you have created multiple instances of your static web app using the `Static Web App VSCode Extension`. Please log in to your Azure Account and remove the duplicate static web apps. Below is an example from the portal:

![image](https://github.com/microsoft/SATechnicalOnboarding/assets/101401469/5e73f140-16c7-45d8-b104-0c0cc177761e)

**Comment by AnthonyByansi** [comment]
To avoid further issues like the one mentioned, please update your Portfolio site from the codespaces, push the changes to the remote repository, and then deploy the site to Azure using the Azure portal by following these [instructions](https://github.com/microsoft/SATechnicalOnboarding/blob/main/technical-onboarding-instructions.md#optional-creating-an-azure-static-web-app-from-an-existing-github-respository)
