### ISSUE TITLE
ci: add Azure Static Web Apps workflow file 

### ISSUE THREAD

**Issue by mukprabhakar** [microsoft/SATechnicalOnboarding#132]
![Screenshot 2024-05-07 232805](https://github.com/microsoft/SATechnicalOnboarding/assets/133365427/4ec1afa5-606a-4bf1-9d82-c699bcd6808d)
![Screenshot 2024-05-07 232828](https://github.com/microsoft/SATechnicalOnboarding/assets/133365427/b49f3e47-0ce3-4ac2-984b-440fd550f88a)
 Shows this type of error

**Comment by AnthonyByansi** [comment]
Hi @mukprabhakar. You shouldn't be experiencing this issue if you had followed the instructions precisely at https://github.com/microsoft/SATechnicalOnboarding/issues/131#issuecomment-2098495557

I've messaged you on Teams for additional assistance.
