### ISSUE TITLE
Issue after hosting website on azure after following Technical Onboarding process

### ISSUE THREAD

**Issue by vaishnavi192** [microsoft/SATechnicalOnboarding#133]
I followed the whole process and my website is ready but it is shown as "your site will be ready soon" since 1-2 weeks on this link https://gray-bay-0c2b65f00.5.azurestaticapps.net/

![image](https://github.com/microsoft/SATechnicalOnboarding/assets/117008958/cb8045e3-4c8c-4ed3-b7c5-0dc7a29b253a)
 My website is already ready and can be accessed here https://automatic-acorn-g9qrv649w7qcpvxr-1234.app.github.dev/
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/117008958/b0d0e721-35be-4cbb-bc38-6e2e418c2166)

I have only 3 days left for completing technical onboarding process, Trying to solve this issue since few weeks but not able to solve it. Please help

**Comment by AnthonyByansi** [comment]
Hi @vaishnavi192 Facing this issue suggests that the deployment configurations may not have been set up correctly.
Most importantly, you need the [package.json](https://github.com/microsoft/SATechnicalOnboarding/blob/main/technical-onboarding-instructions.md#optional-creating-an-azure-static-web-app-from-an-existing-github-respository) file setup correctly for your site to be live.
