### ISSUE TITLE
How to see my Badge on Microsoft Student Learn Ambassador

### ISSUE THREAD

**Issue by ldneal** [microsoft/SATechnicalOnboarding#134]

**Comment by AnthonyByansi** [comment]
Hi @ldneal 

Please login to your[ MVP portal](https://mvp.microsoft.com/en-US/account/) and click `view profile` like so;
![view-profile](https://github.com/microsoft/SATechnicalOnboarding/assets/101401469/9a65b133-e831-432b-a50c-4fad25399cc4)

Your badge will be visible to the right like so;
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/101401469/453248d7-130d-4b85-b8a6-f8afe298dd8d)

I hope that helps 😊
