### ISSUE TITLE
Onboarding Compelete not yet get confirmation

### ISSUE THREAD

**Issue by Zahoorahmed2003** [microsoft/SATechnicalOnboarding#136]
I have completed all the necessary steps that are required for onboarding process but yet to recieve confirmation email and today i have received that i haven't done onboarding process yet i am requesting SACoordinator to look in to this matter.
Thank you

**Comment by AnthonyByansi** [comment]
Hi @Zahoorahmed2003 Please reach out to the SA-coordinator on teams to have you assisted
Utilize the Search option on teams to locate the SA-coordinator profile
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/101401469/4f6a70f9-982a-4ff8-8aba-ed2f521a52bb)
