### ISSUE TITLE
Build and deploy issue

### ISSUE THREAD

**Issue by anands29-mac** [microsoft/SATechnicalOnboarding#138]
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/141543499/ebfd7864-f99b-4327-997a-46debc43e764)
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/141543499/3aad7a40-d015-4a48-bb42-9ec8f4b624b0)
Hi there, I've been facing this issue for so many days, even though I've watched the videos and followed the exact instructions given

**Comment by AnthonyByansi** [comment]
Hi @anands29-mac 
Had you looked at this section of the [technical onboarding](https://github.com/microsoft/SATechnicalOnboarding/blob/main/technical-onboarding-instructions.md#optional-creating-an-azure-static-web-app-from-an-existing-github-respository) especially on the `build preset` configuration?

Also please text me through teams `[Byansi Anthony]` so I can help as fast as I can. Thanks!
