### ISSUE TITLE
Regarding deployment of the website

### ISSUE THREAD

**Issue by Cyberspy27** [microsoft/SATechnicalOnboarding#140]
I followed the instructions as said for the onboarding process but after the deployment process it is not showing the website made. Instead it's showing the template only which was given ... Can anyone send a video with proper steps followed

**Comment by AnthonyByansi** [comment]
hi @Cyberspy27 

The reason as to why you're; seeing a default template might be because you didn't setup your deployment configuration properly. Please re-visit the following section of the [Deploy your static app on Azure](https://github.com/microsoft/SATechnicalOnboarding/blob/main/technical-onboarding-instructions.md#optional-creating-an-azure-static-web-app-from-an-existing-github-respository) and take a keen look at the deployment details you need to provide.

Should you need further assistance, don't hesitate to reach out.

**Comment by Cyberspy27** [comment]
I tried but still its not happening can you please assist me anyway because the submission is on 15th

**Comment by AnthonyByansi** [comment]
Hi @Cyberspy27 
Please send me[Byansi Anthony] a text on teams so I can help

**Comment by Cyberspy27** [comment]
Can you send the link for the teams ?

**Comment by Cyberspy27** [comment]
Your name is not showing in the teams

**Comment by AnthonyByansi** [comment]
Let me know your username so I can reach out

**Comment by Cyberspy27** [comment]
Madhumanti D

**Comment by Cyberspy27** [comment]
Can you help me please ?

**Comment by AnthonyByansi** [comment]
Please share me your MLSA email. I reach out to you ASAP!

**Comment by Cyberspy27** [comment]
Vaibhavi.Yadav@studentambassador.com

**Comment by Cyberspy27** [comment]
Here is the MSLA email

**Comment by Cyberspy27** [comment]
Hello Sir

**Comment by Cyberspy27** [comment]
Any update regarding the portfolio?

**Comment by Cyberspy27** [comment]
Actually the date of submission is on 15th and my portfolio is not deployed

**Comment by AnthonyByansi** [comment]
Hi @Cyberspy27 

I messaged you via Teams yesterday and have not received a response yet. I'm eager to assist as soon as you reply. 

Meanwhile, please ensure you double-check the configurations in the `package.json` file. It's possible that the details provided in the template were not updated to your personal information.

![github-pages-deploy](https://github.com/microsoft/SATechnicalOnboarding/assets/101401469/bf0b2d31-16ac-4019-b293-8e955ef3c040)

**Comment by Cyberspy27** [comment]
But no message message came on Teams

**Comment by Cyberspy27** [comment]
I have send email to you to your Microsoft account through my mail Vaibhavi.Yadav@studentambassador.com

**Comment by AnthonyByansi** [comment]
@Cyberspy27 Double check your teams chats
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/101401469/cbf20578-c6fc-4b30-ba5b-efe1cd7ae877)
