### ISSUE TITLE
Issue regarding the Deployment of my Portfolio site.

### ISSUE THREAD

**Issue by anijit-mlsa** [microsoft/SATechnicalOnboarding#144]
![Screenshot 2024-06-15 102436](https://github.com/microsoft/SATechnicalOnboarding/assets/172510130/1153197c-11d6-4c5d-beb8-298e2e68c663)

The message says that the deployment of my site is sucessfull but is not providing me with any further links.

**Comment by AnthonyByansi** [comment]
Hi @anijit-mlsa 
Well we addressed this issue on teams together. Let me know if you face any other issue. I will be happy to help!

**Comment by anijit-mlsa** [comment]
Yes, the issue is solved now.
