### ISSUE TITLE
Doubt: LEARN paths

### ISSUE THREAD

**Issue by SurajPratap10** [microsoft/SATechnicalOnboarding#29]
- I have completed 1 `Learn` path on **Microsoft Azure Fundamentals: Describe cloud concepts**, so I wanted to ask that is this enough for my automated promotion to `Alpha` level after 2 weeks.
- I will be doing more `Learn paths` in a few days, just clarifying my doubt as I am a new **MLSA**.
.
![image](https://user-images.githubusercontent.com/92919173/233467701-44e3b4b2-068d-4cbe-9a0e-6312c96112b1.png)

**Comment by SalemTracey** [comment]
No worries.
Thank you for your energy and excitement.
Welcome to the program.
