### ISSUE TITLE
Invalid Token Error

### ISSUE THREAD

**Issue by Prahlad08s** [microsoft/SATechnicalOnboarding#35]
I am trying to deploy my static website through GitHub Code Spaces....but it is throwing me Invalid Token error.

Error Message: Repository token is invalid. Provided token has invalid permissions and cannot be used to setup GitHub Actions CI/CD. Admin rights are required for the repo.

 I have created personal access token for that repo and have given all the permissions including the admin rights, but it stills throughs the same error.

I have tried all the possible ways am much as I can.

**Comment by cyberpsychooo** [comment]
same here

**Comment by Michaela-Ivanova** [comment]
Same here! I don't even know how to create  personal access token for that repo and to give all the permissions including the admin rights. Can you explain how you did that? 

Also I found another person commenting on the same issue and said it worked for them to open "vscode.dev". This is the mobile Version of Visual Studio. There you can import your GitHub-Projects and then publish from there on. For me this is not working, but I hope it works for you.

**Comment by AnthonyByansi** [comment]
Hey @Prahlad08s, @cyberpsychooo, @Michaela-Ivanova be sure to check https://github.com/microsoft/SATechnicalOnboarding/discussions/20#discussioncomment-5755127
