### ISSUE TITLE
Can anyone help fix me this issue. I have followed through all the instructions also but still it keeps showing me the same issue.

### ISSUE THREAD

**Issue by MadhavGaur14** [microsoft/SATechnicalOnboarding#38]
![Screenshot (1)](https://github.com/microsoft/SATechnicalOnboarding/assets/117013332/096ae4d4-64c3-4162-bbc8-12b2e9aa44d6)

**Comment by Bakugo90** [comment]
@MadhavGaur14  I have the same problem here. "RepositoryToken is invalid. Provided token has invalid permissions and cannot be used to setup Github Action CI/CD. Admin rights are required for the repository."

**Comment by SalemTracey** [comment]
HI @MadhavGaur14 please see this thread for assistance https://github.com/microsoft/SATechnicalOnboarding/discussions/20#discussioncomment-5755127

**Comment by ademikel** [comment]
Same issue here

**Comment by AnthonyByansi** [comment]
@ademikel I believe https://github.com/microsoft/SATechnicalOnboarding/discussions/20#discussioncomment-5755127 has gotten the solution to that
