### ISSUE TITLE
Error deploying my web application

### ISSUE THREAD

**Issue by andreagori** [microsoft/SATechnicalOnboarding#43]
Hello :) , this is my first time here. I have been stuck with these for a couple of days. I don't know what I did wrong, and the console doesn't give me more explication of why is not working. Do you have any idea of what could it be? 
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/115431777/613723ee-f3d5-44ef-953c-3da4d4351215)

I deleted the others and make a new one but the same mistake happens again.

**Comment by ManuSquall** [comment]
Hello and welcome @andreagori , going to check it on my side and will come back to u 👍🏿:-)

**Comment by AnthonyByansi** [comment]
@andreagori It looks you hadn't signed into your Azure Account in VScode, if it persists, resort to working from your local machine and have the changes pushed to the remote branch, also provision your azure resource from the Azure portal, that will ease on the deployment process.
