### ISSUE TITLE
The app build failed to produce artifact folder: 'build'. Could help me as I am not aware about how this things work in webdev

### ISSUE THREAD

**Issue by yuvraaj2002** [microsoft/SATechnicalOnboarding#51]
![image](https://github.com/microsoft/SATechnicalOnboarding/assets/123289647/be2731ff-446f-4b67-b3f1-aba38506914e)

**Comment by AnthonyByansi** [comment]
@yuvraaj2002 did you trigger `npm run build` in your CodesSpace terminal ?
