### ISSUE TITLE
Not able to see the  changes 

### ISSUE THREAD

**Issue by ayushii06** [microsoft/SATechnicalOnboarding#54]
Actually i am able to deploy my site but when i open my site, it shows the original one not the changed one...can [anyone](url) help?

**Comment by hamitsehjal** [comment]
Hey, @ayushii06, when `npm start` runs, your site is running within your Codespace, and it creates a unique URL for you to access your site. So, my question to you is - Which URL do you use to access your site??

Within your Codespace, in the bottom section, you will see a "PORTS" tab where you will see your unique URL generated in the "Local Address" column after the `npm start` is completed. That is the URL you need to access. 

Something Similar to this:

![example_url](https://github.com/microsoft/SATechnicalOnboarding/assets/73131093/1252edc0-ad00-4040-92aa-c33439c39e92)
