### ISSUE TITLE
PORT 1234 COULD NOT BE USED

### ISSUE THREAD

**Issue by peterkahumu** [microsoft/SATechnicalOnboarding#59]
Hello, when I try to run npm start, a message, 'port 1234 could not be used' appears and the operation is forwarded to another port. How can I solve this? I really need the static web app to run on port 1234

**Comment by divital-coder** [comment]
I think you should try developing your Static Web App in react in your local visual studio code instance, instead of github codespaces, which might be causing some weird things with port forwarding.
