### ISSUE TITLE
Facing this error

### ISSUE THREAD

**Issue by truptiikanade** [microsoft/SATechnicalOnboarding#65]
![mlsaerror](https://github.com/microsoft/SATechnicalOnboarding/assets/148260906/0da3489c-d7e0-49a2-89f0-8fe0ad881364)
![mlsaerror](https://github.com/microsoft/SATechnicalOnboarding/assets/148260906/8015b39c-57a6-45dd-ab52-97a96e7c8c0e)

**Comment by AnthonyByansi** [comment]
Hello, @truptiikanade. Would you be available to review the discussion at https://github.com/microsoft/SATechnicalOnboarding/discussions/20? It appears to contain a solution to the issue at hand.
