### ISSUE TITLE
Error when trying to create Azure resource

### ISSUE THREAD

**Issue by HebbyHebz** [microsoft/SATechnicalOnboarding#90]
When I try creating a new Azure resource/signing into Azure, I click on create a new resource, and I get this error: 

`Error running command azureResourceGroups.createResource: command 'azureResourceGroups.createResource' not found. This is likely caused by the extension that contributes azureResourceGroups.createResource.`

![image](https://github.com/microsoft/SATechnicalOnboarding/assets/42718288/e35c3e45-b934-4b3f-952c-ec8140a6840e)

**Comment by theyashsisodiya** [comment]
Try to authenticate your azure via login and remember before creating resources you have to build static app first.
