### ISSUE TITLE
Got issue in deploying my portfolio

### ISSUE THREAD

**Issue by bhavishyasingla1** [microsoft/SATechnicalOnboarding#95]
<img width="454" alt="image" src="https://github.com/microsoft/SATechnicalOnboarding/assets/113583143/d7a4ad31-4b18-4c89-8643-b5d51da0f914">
<img width="594" alt="image" src="https://github.com/microsoft/SATechnicalOnboarding/assets/113583143/fdf9a2ac-a92e-4438-861b-c590b0ebaa99">
<img width="644" alt="image" src="https://github.com/microsoft/SATechnicalOnboarding/assets/113583143/c79da8b2-26a3-4c84-b85b-9abd4c779157">
<img width="637" alt="image" src="https://github.com/microsoft/SATechnicalOnboarding/assets/113583143/c732833f-feb2-4d10-ade3-aa7e1eb699ee">

**Comment by theyashsisodiya** [comment]
Can you tell us what's the step did you follow?

**Comment by bhavishyasingla1** [comment]
> Can you tell us what's the step did you follow?

https://youtu.be/ODjpaUd4GtM?si=MjtBsI7c8vxdgZAX I followed this video

**Comment by Ayushpandey4085** [comment]
same issue as given above please resolve this

**Comment by AnthonyByansi** [comment]
Hi @Ayushpandey4085 the steps we updated. please, delete the `.github/worflow` folder from your repository and start off a new deployment process by following[ these instructions](https://github.com/microsoft/SATechnicalOnboarding/blob/main/technical-onboarding-instructions.md). If you ever find more difficulties to this, don't hesitate to reach out to me on discord and I will have you helped
