### ISSUE TITLE
I don't have enough storage

### ISSUE THREAD

**Issue by ghost** [microsoft/SATechnicalOnboarding#97]
Hey. I am unable to use codespaces because it is saying I do not have enough storage to which I had to delete my entire repo. I also have no experience in coding. Can someone tell me what else I have to delete please and thank you.

**Comment by AnthonyByansi** [comment]
Hi @BiancaM22 Do you mind taking a screenshot of the issue your facing? Since you're new to coding, I can't assume that you used up the free monthly codespaces minutes.
